config/routes.rb
Tyro::Application.routes.draw do
  
  match 'feed' => 'home#feed'
  match 'display/playlist' => 'display#playlist'
  
  get 'home' => 'home#index', :as => :home
  get 'schedule' => 'home#schedule', :as => :schedule
  get 'sources' => 'home#sources', :as => :sources
  get 'playlist' => 'home#playlist', :as => :playlist
  get 'news' => 'home#news', :as => :news
  get 'blog' => 'blogs#index', :as => :blog
  get 'podcast' => 'podcasts#index', :as => :podcast
  
  get 'update_playlist' => 'home#update_playlist'
  get 'update_current_events' => 'home#update_current_events'  
  get 'update_next_event' => 'home#update_next_event'  
  
  get '/livecam/:cam' => 'home#livecam', :as => :livecam

  match 'explore(/:search_type)' => 'home#explore', :as => :explore
  
  resources :tags, :only => [:index, :show]
    
  get 'about' => 'about#history', :as => :about
  get 'contact' => 'about#contact', :as => :contact
  get 'channels' => 'about#channels', :as => :channels
  get 'submissions' => 'about#submissions', :as => :submissions
  
  get 'stream(/:channel)' => 'home#stream', :as => :stream
  get 'stream/audio/:channel' => 'home#channel_redirect'
  get 'streams/audio/:channel' => 'home#channel_redirect'
    
  resources :shows, :only => :show do
    get 'update_playlist', :on => :collection, :defaults => { :format => :js }
  end
  
  resources :events, :only => [:index, :show] do
    get 'birn1' => 'events#index', :event_type => 'birn1', :on => :collection, :as => :birn1
    get 'birn2' => 'events#index', :event_type => 'birn2', :on => :collection, :as => :birn2
    get 'birn-presents' => 'events#index', :event_type => 'birn-presents', :on => :collection, :as => :birn_presents
  end
    
  get 'join' => 'cp/signups#new', :as => :join
  
  namespace :cp do
    
    match 'login' => 'sessions#new', :as => :login
    match 'logout' => 'sessions#destroy', :as => :logout
    match 'resources' => 'home#resources', :as => :resources
    match 'tin_news' => 'home#tin_news', :as => :tin_news
    
    get "guest-request" => "guest_requests#new", :as => :guest_request
    post "guest-request" => "guest_requests#create", :as => :guest_request
    
    resources :sessions, :only => [:new, :create, :destroy] do 
      get 'emails', :as => :emails, :on => :collection
    end
    
    resource :profile, :only => [:show, :edit, :update] do
      get 'strikes'
      get 'edit_password'
      put 'update_password'
      get 'training_progress'
    end
    
    resources :signups, :news_posts
    resources :static_contents, :only => [:index, :edit, :update]
    
    resources :password_resets, :only => [:new, :create, :edit, :update]
    resources :comments, :except => [:index, :show, :new]
    resources :training_steps, :except => [:show]
        
    resources :schedule_events do
      resources :playlist_entries do
        match 'playlist', :as => :playlist, :on => :collection
      end # playlist_entries
      put 'move' => 'schedule_events#move', :on => :member
      collection do 
        get 'schedule'
        get 'calendar'
        post 'recur'
      end
    end
        
    resources :events do
      get 'playlist', :on => :member
    end
    
    resources :forums, :except => :show do
      resources :topics, :only => [:index, :new, :create] #added index for backwards-compatibility
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
    end #forums
    
    resources :topics, :except => :show do
      resources :messages, :only => [:index, :new, :create] #added index for backwards-compatibility
      collection do
        get 'unread'
        get 'mark_read'
      end
      
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
      get '/' => 'messages#index'#, :as => :messages 
    end #topics
    
    resources :messages, :except => :show
    
    resources :problem_reports do      
      member do
        post 'toggle_status'
        get 'comments' => 'problem_reports#show'
      end
      
      resources :comments, :only => :create
    end #problem reports
    
    resources :users do
      resources :comments, :only => :create
      resources :strikes, :except => :show do
        post 'toggle_resolved', :on => :member
      end
      resource :training_progress, :only => [:show, :edit, :update], :controller => 'training_progress'
      
      member do
        get 'edit_password'
        put 'update_password'
        
        get 'comments'
        
        get 'edit_remove'
        put 'remove'
        
        get 'edit_permissions'
        put 'update_permissions'
        
        get 'manage'
        put 'update_manage'
        
        put 'resend_welcome'
      end
      
      collection do
        get 'search'
        get 'new_multiple'
        post 'create_multiple'
      end
    end #users
        
    resources :shows do
      resources :posts, :except => :show
      resources :shouts, :substitutes
      resources :schedule_events, :only => [:index, :new, :create]
      
      collection do
        get 'search'
        get 'full_schedule'
      end
      
      member do
        get 'schedule'
        get 'playlist(/:schedule_event_id)' => 'shows#playlist', :as => :playlist
        get 'edit_manage'
        put 'update_manage'
      end
    end # shows
    
    root :to => 'home#index'  

    if Rails.env.production?
      match '*path' => 'home#index'
    end

  end #cp
  
  root :to => 'home#index'
  
  if Rails.env.production?
    match '*path' => 'home#index'
  end

end

app/views/shared/_blogs.html.erb
<!--
<div id="blogs" class="widget">
	<h3>Latest Blogs</h3>
	Latest Blogs are listed here. <a href="#">This is a link</a>
</div>
-->

app/views/shared/_contact.html.erb
<% cache "sc_contact_box" do %>
	<% contact ||= '' %>
	<div id="contact" class="widget contact">
		<h3>Contact</h3>
		<div class="content">
			<%= contact.content.present? ? contact.content.html_safe : "No contact info yet." %>
		</div>
	</div> <!-- contact -->
<% end %>

app/views/shared/_dj_profile.html.erb
<div class="dj-container">
	<div class="name"><%= record.dj_name %></div><br />
	<%= link_to display_avatar(record, 'small'), record.avatar.url(:original), :class => 'lightbox', :title => record.dj_name %><br />
	<%= record.about %>
</div>

app/views/shared/_explore.html.erb
<div id="explore" class="widget">
	<h3>Explore</h3>
	<div class="content">
		<form action="<%= explore_path %>" method="get">
			<%= text_field_tag 'query', nil, :placeholder => "Looking for something?" %>
			<%= submit_tag "Go", :name => nil %>
		</form>
	</div>
</div>

app/views/shared/_featured_dj.html.erb
<div id="featured-dj" class="widget">
	<h3>Featured DJ</h3>
	<div class="content">
		<% if record %>
			<%= render :partial => 'shared/dj_profile', :locals => { :record => record } %>
		<% else %>
			There is currently no Featured DJ.
		<% end %>
	</div>
</div>

app/views/shared/_links.html.erb
<% cache "sc_links" do %>
	<div id="links" class="widget">
		<h3>Links</h3>
		<div class="small">
			<%= links.content.present? ? links.content.html_safe : "No links to list." %>
		</div>
	</div>
<% end %>

app/views/shared/_mbj.html.erb
<div id="music-business-journal" class="widget">
	<h3>Music Business Journal</h3>
	<% records.each do |item| %>
		<div class="item small linked">
			<%= link_to item.title, item.link %><br />
			<div class="meta right"><%= distance_of_time_in_words(Time.zone.now, item.date) %> ago</div>
			<div class="clear"></div>
		</div>
	<% end %>
	<%= no_records_check(records, "Feed Items", :message => "There is no feed data.")%>
</div> <!-- mbj -->

app/views/shared/_news.html.erb
<% records.each do |post| %>
	<h3><%= post.title %></h3>
	<div class="content-box news description">
		<%= post.body.html_safe %>
	</div>
<% end %>

app/views/shared/_playlist_entry.html.erb
<% with_show ||= false %>
<div class="entry small" data-time="<%= playlist_entry.created_at.to_i %>">
	<span class="time small"><%= pretty_date(playlist_entry.created_at, :only_time => true) %></span>
	<span class="info"><%= playlist_entry.title %></span>
	<span class="meta small">by</span>
	<span class="info"><%= playlist_entry.artist %></span>
	<span class="meta small from"><% if playlist_entry.album.present? %>from<% end %></span>
	<span class="info"><%= playlist_entry.album %></span>
	<% if with_show and playlist_entry.schedule_event.present? %>
		<span class="meta small">on show</span>
		<span class="info"><%= link_to playlist_entry.schedule_event.schedulable.title, playlist_entry.schedule_event.schedulable %></span>
	<% end %>
	<%= link_to image_tag("icons/itunes.png", :alt => "Search for this song in iTunes", :class => 'itunes-icon'), 
		"itms://phobos.apple.com/WebObjects/MZSearch.woa/wa/advancedSearchResults?artistTerm=#{playlist_entry.artist.gsub(' ', '%20')}&songTerm=#{playlist_entry.title.gsub(' ', '%20')}" %>
</div>

app/views/shared/_todays_events.html.erb
<div id="schedule-today" class="widget">
	<h3>Schedule</h3>
	<% if record.empty? %>
		<div class="content">
			We're taking a quick breather...<br />
			Check out our <%= link_to "Schedule", schedule_path %> to see when we'll be back live!
		</div>
	<% else %>
		<% record.group_by { |e| e.starts_at.strftime('%A') }.each do |day, events| %>
			<div class="day-header"><%= day %></div>
			<% events.each do |event| %>
				<div class="item event small linked last-link">
					<div class="time small">
						<% if current_events.include? event
							event_type = ScheduleEvent.get_event_type(event.event_type) %>
							<%= link_to "LIVE!", stream_path(:channel => event_type[:channel]), :class => 'stream-link', "data-channel" => event_type[:channel] %>
						<% else %>
							<%= pretty_date(event.starts_at, :only_time => true) %>
						<% end %>
					</div>
					<div class="title">
						<%= link_to event.title, polymorphic_url(event.schedulable) %>
					</div>
				</div> <!-- item -->
			<% end #events.each %>
		<% end #record.group_by %>
	<% end #record.empty? %>
	<div class="item small linked">
		<%= link_to "Full Schedule &raquo;".html_safe, schedule_path, :class => 'right' %>
		<div class="clear"></div>
	</div>
</div> <!-- schedule-today -->

app/views/shared/_twitter.html.erb
<div id="twitter" class="widget">
	<script src="http://widgets.twimg.com/j/2/widget.js"></script>
	<script>
	new TWTR.Widget({
	  version: 2,
	  type: 'profile',
	  rpp: 1,
	  interval: 30000,
	  width: 180,
	  height: 250,
	  theme: {
	    shell: {
	      background: '#333333',
	      color: '#edf6cf'
	    },
	    tweets: {
	      background: '#000000',
	      color: '#edf6cf',
	      links: '#e85f29'
	    }
	  },
	  features: {
	    scrollbar: false,
	    loop: false,
	    live: false,
	    hashtags: false,
	    timestamp: false,
	    avatars: false,
	    behavior: 'all'
	  }
	}).render().setUser('birn').start();
	</script>
</div> <!-- twitter -->