config/routes.rb
Tyro::Application.routes.draw do
  
  match 'feed' => 'home#feed'
  match 'display/playlist' => 'display#playlist'
  
  get 'home' => 'home#index', :as => :home
  get 'schedule' => 'home#schedule', :as => :schedule
  get 'sources' => 'home#sources', :as => :sources
  get 'playlist' => 'home#playlist', :as => :playlist
  get 'news' => 'home#news', :as => :news
  get 'blog' => 'blogs#index', :as => :blog
  get 'podcast' => 'podcasts#index', :as => :podcast
  
  get 'update_playlist' => 'home#update_playlist'
  get 'update_current_events' => 'home#update_current_events'  
  get 'update_next_event' => 'home#update_next_event'  
  
  get '/livecam/:cam' => 'home#livecam', :as => :livecam

  match 'explore(/:search_type)' => 'home#explore', :as => :explore
  
  resources :tags, :only => [:index, :show]
    
  get 'about' => 'about#history', :as => :about
  get 'contact' => 'about#contact', :as => :contact
  get 'channels' => 'about#channels', :as => :channels
  get 'submissions' => 'about#submissions', :as => :submissions
  
  get 'stream(/:channel)' => 'home#stream', :as => :stream
  get 'stream/audio/:channel' => 'home#channel_redirect'
  get 'streams/audio/:channel' => 'home#channel_redirect'
    
  resources :shows, :only => :show do
    get 'update_playlist', :on => :collection, :defaults => { :format => :js }
  end
  
  resources :events, :only => [:index, :show] do
    get 'birn1' => 'events#index', :event_type => 'birn1', :on => :collection, :as => :birn1
    get 'birn2' => 'events#index', :event_type => 'birn2', :on => :collection, :as => :birn2
    get 'birn-presents' => 'events#index', :event_type => 'birn-presents', :on => :collection, :as => :birn_presents
  end
    
  get 'join' => 'cp/signups#new', :as => :join
  
  namespace :cp do
    
    match 'login' => 'sessions#new', :as => :login
    match 'logout' => 'sessions#destroy', :as => :logout
    match 'resources' => 'home#resources', :as => :resources
    match 'tin_news' => 'home#tin_news', :as => :tin_news
    
    get "guest-request" => "guest_requests#new", :as => :guest_request
    post "guest-request" => "guest_requests#create", :as => :guest_request
    
    resources :sessions, :only => [:new, :create, :destroy] do 
      get 'emails', :as => :emails, :on => :collection
    end
    
    resource :profile, :only => [:show, :edit, :update] do
      get 'strikes'
      get 'edit_password'
      put 'update_password'
      get 'training_progress'
    end
    
    resources :signups, :news_posts
    resources :static_contents, :only => [:index, :edit, :update]
    
    resources :password_resets, :only => [:new, :create, :edit, :update]
    resources :comments, :except => [:index, :show, :new]
    resources :training_steps, :except => [:show]
        
    resources :schedule_events do
      resources :playlist_entries do
        match 'playlist', :as => :playlist, :on => :collection
      end # playlist_entries
      put 'move' => 'schedule_events#move', :on => :member
      collection do 
        get 'schedule'
        get 'calendar'
        post 'recur'
      end
    end
        
    resources :events do
      get 'playlist', :on => :member
    end
    
    resources :forums, :except => :show do
      resources :topics, :only => [:index, :new, :create] #added index for backwards-compatibility
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
    end #forums
    
    resources :topics, :except => :show do
      resources :messages, :only => [:index, :new, :create] #added index for backwards-compatibility
      collection do
        get 'unread'
        get 'mark_read'
      end
      
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
      get '/' => 'messages#index'#, :as => :messages 
    end #topics
    
    resources :messages, :except => :show
    
    resources :problem_reports do      
      member do
        post 'toggle_status'
        get 'comments' => 'problem_reports#show'
      end
      
      resources :comments, :only => :create
    end #problem reports
    
    resources :users do
      resources :comments, :only => :create
      resources :strikes, :except => :show do
        post 'toggle_resolved', :on => :member
      end
      resource :training_progress, :only => [:show, :edit, :update], :controller => 'training_progress'
      
      member do
        get 'edit_password'
        put 'update_password'
        
        get 'comments'
        
        get 'edit_remove'
        put 'remove'
        
        get 'edit_permissions'
        put 'update_permissions'
        
        get 'manage'
        put 'update_manage'
        
        put 'resend_welcome'
      end
      
      collection do
        get 'search'
        get 'new_multiple'
        post 'create_multiple'
      end
    end #users
        
    resources :shows do
      resources :posts, :except => :show
      resources :shouts, :substitutes
      resources :schedule_events, :only => [:index, :new, :create]
      
      collection do
        get 'search'
        get 'full_schedule'
      end
      
      member do
        get 'schedule'
        get 'playlist(/:schedule_event_id)' => 'shows#playlist', :as => :playlist
        get 'edit_manage'
        put 'update_manage'
      end
    end # shows
    
    root :to => 'home#index'  

    if Rails.env.production?
      match '*path' => 'home#index'
    end

  end #cp
  
  root :to => 'home#index'
  
  if Rails.env.production?
    match '*path' => 'home#index'
  end

end

app/controllers/cp/home_controller.rb
class Cp::HomeController < Cp::BaseController
  
  def index
    @latest_topics = Topic.order('updated_at DESC').limit(5)
    @announcements = Topic.global.limit(3)
    @unread_topics = Topic.unread_by(@current_user)
  end
  
  def resources
    @resources = StaticContent.find_by_text_id('resources')
  end
  
  def tin_news
    @tin_news = StaticContent.find_by_text_id('tin_news')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :get_current_events, :only => [:index, :playlist, :news, :explore, :update_current_events, :update_playlist]
  before_filter :get_next_event, :only => [:index, :update_next_event]
  before_filter :get_channel_descriptions, :except => [:feed, :livecam, :wrongbrowser, :sources, :update_playlist]
  before_filter :get_todays_events, :only => [:index, :playlist, :news, :explore]
  before_filter :get_mbj_feed, :only => [:index, :news]
  before_filter :get_featured_dj, :only => [:index, :playlist, :news, :explore]
  before_filter :get_links, :only => [:index, :news]
  before_filter :get_management, :except => [:feed, :livecam, :wrongbrowser, :sources, :update_playlist]
  before_filter :get_tags, :only => [:index, :playlist, :news]
  before_filter :get_contact, :only => [:index, :playlist, :explore, :news]
  
  respond_to :html, :js, :json
  
  Channels =  [{ :title => "Birn1", :channel => 'birn1', :file => 'channel-1'},
              { :title => "Birn2", :channel => 'birn2', :file => 'channel-2'},
              { :title => "Birn3", :channel => 'birn3', :file => 'channel-3'},
              { :title => "Birn4", :channel => 'birn4', :file => 'channel-4'},
              { :title => "Birn5", :channel => 'birn5', :file => 'channel-5'},
              { :title => "birn-presents", :channel => 'birn-presents', :file => 'birn-presents'}]
              
  def index
    @news_posts = NewsPost.limit(1)
  end
  
  def playlist
    @playlist_entries = PlaylistEntry.page(params[:page]).per(50).order('created_at DESC').includes(:schedule_event)
  end
  
  def feed
    render :text => "No Feed"
  end
  
  def channel_redirect    
    channel = Channels.find{|c| c[:channel] == params[:channel]}
    if channel.present?
      redirect_to "http://streams.thebirn.com/berklee-radio/#{channel[:file]}.m3u"
    else
      redirect_to channels_path
    end
  end
  
  def stream
    @channel = Channels.find{|c| c[:channel] == params[:channel]}
    render :layout => 'minimal'
  end
  
  def explore
    # First, lazy-load any model we want to search.
    @playlist_entries = PlaylistEntry.search(params[:query]).page(params[:page]).per(30)
    @shows = Show.search(params[:query], :field_weights => { :tags => 10, :title => 5, :description => 1 }, :order => 'active DESC, @relevance DESC').page(params[:page]).per(10)
    @events = Event.search(params[:query], :field_weights => { :tags => 10, :title => 5, :description => 1 },
                            :order => :starts_at).page(params[:page]).per(5)
    
    # Array of accepted search types. Order matters - If no param[:search_type] is specified, this is the order that it will look in.
    @search_types = [{ :title => "Shows", :param => 'shows', :response => @shows },
                     { :title => "Playlist", :param => 'playlist', :response => @playlist_entries },
                     { :title => "Events", :param => 'events', :response => @events }]
                  
    # Now check that params[:search_type] is in the accepted types, and return the search type
    @results = @search_types.find { |t| t[:param] == params[:search_type] } if params[:search_type].present?
    
    # If @results is blank (i.e. either params[:search_type] is not accepted, including nil), then run through each search_type and check if the query has any results.
    # this will always be run when visiting /explore without a search_type defined. This will make sure that if there are results for any of the search_types, a "no results" page won't be displayed.
    # "no results" will only be displayed if there are no results at all, or if a search_type is specified and there are no results for that search_type. i.e. /explore/playlist will always *only* search in the Playlists.
    @results = @search_types.find{ |search_type| search_type[:response].present? } if @results.blank?
    
    # Finally, if nothing was found at all, then just return an empty hash so the view can tell the person that "Experimental Electronic Gregorian Chants" isn't a very popular choice.
    respond_with @results ||= {}
    
    rescue Riddle::ConnectionError # If Sphinx is not running.
      redirect_to root_path, :alert => "Our search feature is currently offline. Check back soon."
  end
    
  def sources
    @events = ScheduleEvent.of_schedulable_type(schedulable_type).of_type(event_type)
    @events = @events.after(params['start']) if (params['start'])
    @events = @events.before(params['end']) if (params['end'])
    respond_to do |format|
      format.js { render :json => @events.includes(:schedulable).to_json(:frontpage => true) }
      format.html
    end
  end
  
  def news
    @news_posts = NewsPost.page(params[:page]).per(4)
  end
  
  def update_playlist
    @current_event = ScheduleEvent.find(params[:current_event_id])
    @playlist_entries = @current_event.playlist_entries.order('created_at DESC').limit(5) if @current_events.include? @current_event
    respond_with @playlist_entries
  end
  
  def update_current_events # FIXME this and update_next_event make the Facebook box disappear.
    respond_with @current_events
  end
  
  def update_next_event
    respond_with @next_event
  end
  
  def livecam
    render :layout => 'minimal'
  end
  
  def wrongbrowser
    render :layout => 'minimal'
  end
  
  protected
    def schedulable_type # This will have to be expanded if we add more than the two types.
      params[:source] == 'shows' ? 'Show' : 'Event'
    end
    
    def event_type # this could be a little better
      ScheduleEvent::Types.any? { |t| t[:id] == params[:source] } ? params[:source] : "Birn1"
    end
  
    helper_method :get_no_event_text
    def get_no_event_text
      @no_event_text = StaticContent.find_by_text_id("no_event").content rescue "There is currently no show."
    end

    def get_next_event
      @next_event = Event.where("schedule_events.schedulable_type = 'Event'").next
    end
end

app/views/home/_current_event.html.erb
<div class="current-event" id="<%= current_event.id %>">
	<% event_type = ScheduleEvent.get_event_type(current_event.event_type) 
	   event = current_event.schedulable %>
	<h2 class="with-gradient"><%= link_to "Live on #{event_type[:title]}!", stream_path(:channel => event_type[:channel]), :class => "listen-link", "data-channel" => event_type[:channel] %></h2>

	<% if event.class.to_s == 'Show' %>
		<div class="content-box show">
			<h3><%= link_to event.title, event %>
				<%= livecam_icon %></h3>

			<div class="description">
				<%= link_to display_avatar(event, 'medium'), event %>
				<span class="info"><%= current_event.starts_at.strftime("%l%p") + " - " + current_event.ends_at.strftime("%l%p") %> EST</span>
				<%= event.description.present? ? event.description : "#{event.users.map(&:dj_name).to_sentence} Broadcasting from the BIRN Studios at Berklee!"%>
				<div class="facebook-like-big">
					<fb:like href="http://thebirn.com<%= url_for event %>" ref="<%= truncate(event.to_param) %>" send="false" layout="standard" show_faces="true" width="411px" colorscheme="dark" font="lucida grande"></fb:like>
				</div>
			</div> <!-- description -->
		</div> <!-- content-box -->
		
	<% elsif event.class.to_s == 'Event' %>
		<%= render :partial => 'events/event_info', :locals => { :event => event } %>
	<% end # class check %>
	
	<% if current_event.playlist_entries.present? %>
		<h3>Playlist</h3>
		<div class="playlist refresh" data-current-event-id="<%= current_event.id %>">
			<div class="entries">
				<%= render :partial => 'shared/playlist_entry', :collection => current_event.playlist_entries.order("created_at desc").limit(5) #TODO fix this
				 %>
			</div>
			<div class="small right">
				<%= link_to "View full playlist &raquo;".html_safe, playlist_path %>
			</div>&nbsp;
			<div class="clear"></div>
		</div> <!-- playlist -->
	<% end # event check %>
</div><!-- #current-event -->

app/views/home/_next_event.html.erb
<% event_type = ScheduleEvent.get_event_type(next_event.event_type) %>
<h2 class="with-gradient">Coming Soon on <%= link_to event_type[:title], stream_path(:channel => event_type[:channel]), :class => "listen-link", "data-channel" => event_type[:channel] %></h2>
<%= render :partial => 'events/event_info', :locals => { :event => next_event } %>
<div class="clear"></div>

app/views/home/_no_events.html.erb
<h2 class="with-gradient"><%= link_to "Live on the Air!", stream_path(:channel => 'birn1'), :class => "listen-link", "data-channel" => 'birn1' %></h2>
<div class="content-box show">
	<h3>BIRN Automaton</h3>
	<div class="description">
		<%= image_tag "defaults/DJ-Robot.jpg", :class => 'avatar' %>
		<%= get_no_event_text.html_safe %>
	</div>
</div>

app/views/home/about.html.erb
<div id="left">
	<%= render :partial => 'shared/blogs', :locals => { :records => @blogs }%>
	<%= render :partial => 'shared/twitter' %>
	<%= render :partial => 'shared/mbj', :locals => { :records => @mbj_items } %>
	<%= render :partial => 'shared/links', :locals => { :links => @links } %>
</div> <!-- left -->

<div id="about" class="middle">
	<h2>The Berklee Internet Radio Network</h2>
	<div class="sub-nav">
		<%= link_to "Channels", channels_path, :class => params[:action] == 'channels' ? 'active' : nil %>
		<%= link_to "Contact", contact_path, :class => params[:action] == 'contact' ? 'active' : nil %>
		<%= link_to "About", about_path, :class => params[:action] == 'history' ? 'active' : nil %>
		<%= link_to "Submit Your Music", submissions_path, :class => params[:action] == 'submissions' ? 'active' : nil %>
	</div>
	<%= @content.content.present? ? @content.content.html_safe : "Check back soon for more information." %>	
</div>

<div id="right">
	<%= render :partial => 'shared/explore', :locals => { :tags => @tags } %>
	<%= render :partial => 'shared/todays_events', :locals => { :record => @todays_events, :current_events => @current_events } %>
	<%= render :partial => 'shared/featured_dj', :locals => { :record => @featured_dj } %>
	<%= render :partial => 'shared/contact', :locals => { :contact => @contact } %>
</div> <!-- right -->

app/views/home/explore.html.erb
<div id="explore" class="two-cols">
	<h2 class="with-gradient">Explore</h2>
	<div class="sub-nav">
		<% @search_types.each do |search_type| %>
			<%= link_to search_type[:title], explore_path(request.GET().merge!(:search_type => search_type[:param])), :class => @results[:param] == search_type[:param] ? 'active' : nil %>
		<% end %>
	</div>
	<p>
	<form action="<%= explore_path %>" method="get">
		<strong>What are you looking for?</strong> &nbsp;&nbsp;<%= text_field_tag 'query', params[:query] %>
		<%= submit_tag "Go", :name => nil %>
	</form>
	</p>
	
	<% if @results[:response].present? %>
		<% if @results[:param] == "shows" %>
			<% @results[:response].each do |show| %>
				<div class="content-box show">
					<h3><%= link_to show.title, show %></h2>
					<div class="avatar">
						<%= link_to display_avatar(show, 'medium'), show.avatar.url(:original), :class => 'lightbox', :title => show.title %>
					</div>
					<div class='info'>
						<% if @current_events.any?{|e| e.schedulable == show} %>
							<%= link_to "Live on BIRN1!", stream_path(:channel => 'birn1'), :class => 'stream-link', "data-channel" => 'birn1' %>
						<% elsif show.next.present? %>
							<%= show.next.starts_at.strftime("%As at %l%p EST")%>
						<% else %>
							This show is not scheduled.
						<% end %>
					</div> <!-- .info -->

					<div class='info genre'>
						<%= show.genre.present? ? show.genre : "Music" %>
					</div>
					<div class="description">
						<%= show.description.present? ? show.description : "#{show.users.map(&:dj_name).to_sentence} Broadcasting from the BIRN Studios at Berklee!"%>
					</div>
					<div class="clear"></div>
				</div> <!-- show -->
			<% end %>
			
		<% elsif @results[:param] == "playlist" %>
			<div class="playlist">
				<% @results[:response].group_by{|e| e.created_at.strftime("%B %Y")}.each do |date, entries| %>
					<h3><%= date %></h3>
						<%= render :partial => 'shared/playlist_entry', :collection => entries, :locals => { :with_show => true } %>
				<% end %>
			</div>
			
		<% elsif @results[:param] == "events" %>
			<% @results[:response].each do |event| %>
				<%= render :partial => 'events/event_info', :locals => { :event => event, :hide_facebook => true } %>
			<% end %>
		
		<% else %>
			<% @results[:response].each do |result| %>
				<p>
					<% result.attributes.each do |key, value| %> 
						<strong><%=key%></strong>: <%=value%><br />
					<% end %>
				</p>
			<% end %>
		<% end # type check %>
	<div class="right<%= ' hidden' if @results[:response].num_pages < 2 %>">More: <%= paginate @results[:response] %></div>
	
	<% else # no results %>
		Your search didn't return anything! You can try to:
		<ul>
			<% if params[:search_type].present? %>
				<li>Check different areas: 
					<ul>
						<% @search_types.reject{|t| t[:param] == params[:search_type]}.each do |search_type| %>
							<li><%= link_to search_type[:title], explore_path(request.GET().merge!(:search_type => search_type[:param])) %></li>
						<% end %>
					</ul>
				</li>
			<% end %>
			<li>Refine your search: Make it more generic or remove common words ("the", "or", "and", etc.)</li>
			<li>Search for something else you're interested in!</li>
		</ul>
	<% end %>
</div>

<div id="right">
	<%= render :partial => 'shared/todays_events', :locals => { :record => @todays_events, :current_events => @current_events } %>
	<%= render :partial => 'shared/featured_dj', :locals => { :record => @featured_dj }%>
	<%= render :partial => 'shared/contact', :locals => { :contact => @contact } %>
</div> <!-- right -->

app/views/home/index.html.erb
	<div id="left">
		<%= render :partial => 'shared/blogs', :locals => { :records => @blogs }%>
		<%= render :partial => 'shared/twitter' %>
		<%= render :partial => 'shared/mbj', :locals => { :records => @mbj_items } %>
		<%= render :partial => 'shared/links', :locals => { :links => @links } %>
	</div> <!-- left -->
	
	<div class="middle">
		<div id="current-events">
			<% unless @current_events.blank? %>
				<%= render :partial => 'current_event', :collection => @current_events %>
			<% else %>
				<%= render "no_events" %>
			<% end %>
			<div class="clear"></div>
		</div>
		
		<div id="next-event">
			<% if @next_event.present? %>
				<%= render :partial => 'next_event', :object => @next_event %>
			<% end %>
		</div>
		
		<div id="news-items">
			<h2 class="with-gradient">News</h2>
			<% if @news_posts.present? %>
				<%= render :partial => 'shared/news', :locals => { :records => @news_posts } %>
				<div class="sub-nav below right">
					<%= link_to "More News &raquo;".html_safe, news_path %>
				</div>
			<% end %>
		</div>

	</div> <!-- middle -->
	
	<div id="right">
		<%= render :partial => 'shared/explore', :locals => { :tags => @tags } %>
		<%= render :partial => 'shared/todays_events', :locals => { :record => @todays_events, :current_events => @current_events } %>
		<%= render :partial => 'shared/featured_dj', :locals => { :record => @featured_dj } %>
		<%= render :partial => 'shared/contact', :locals => { :contact => @contact } %>
	</div> <!-- right -->

app/views/home/livecam.html.erb
<%= content_for :title, "BIRN Live Cam" %>
<%= content_for :header do %>
	<script type="text/javascript">
		function refreshImage() {
			$('#webcam-image').fadeOut(400);
			setTimeout(function() {
				$('#webcam-image').attr('src', "http://media.thebirn.com/webcam/<%=params[:cam]%>.jpg?" + Math.random()).fadeIn(400);
			}, 300);
		}
		$(document).ready(function() {
			setInterval('refreshImage()', 30000);
		});
	</script>
<% end %>

<div id="webcam">
	<h3><%= "Broadcast Room" if params[:cam] == "broadcast" %>
	 	<%= "Live Room" if params[:cam] == 'live' %></h3>
	<%= image_tag "http://media.thebirn.com/webcam/#{params[:cam]}.jpg", :id => 'webcam-image' %><br />
	<%= link_to 'Broadcast', livecam_path(:cam => 'broadcast') %> - <%= link_to 'Live Room', livecam_path(:cam => 'live') %>
</div> <!-- #webcam -->

app/views/home/news.html.erb
<div id="left">
	<%= render :partial => 'shared/blogs', :locals => { :records => @blogs }%>
	<%= render :partial => 'shared/twitter' %>
	<%= render :partial => 'shared/mbj', :locals => { :records => @mbj_items } %>
	<%= render :partial => 'shared/links', :locals => { :links => @links } %>
</div> <!-- left -->

<div id="news" class="middle">
	<h2 class="with-gradient">BIRN News</h2>
	<% if @news_posts.present? %>
		<%= render :partial => 'shared/news', :locals => { :records => @news_posts } %>
		<%= paginate @news_posts %>
	<% end %>
	<%= no_records_check(@news_posts, "News Posts") %>
</div> <!-- middle -->

<div id="right">
	<%= render :partial => 'shared/explore', :locals => { :tags => @tags } %>
	<%= render :partial => 'shared/todays_events', :locals => { :record => @todays_events, :current_events => @current_events } %>
	<%= render :partial => 'shared/featured_dj', :locals => { :record => @featured_dj } %>
	<%= render :partial => 'shared/contact', :locals => { :contact => @contact } %>
</div> <!-- right -->

app/views/home/schedule.html.erb
<%= content_for :javascript do %>
	<script type="text/javascript">
		$(document).ready(function() {

			var date = new Date();
			var d = date.getDate();
			var m = date.getMonth();
			var y = date.getFullYear();

			var schedule = $('#schedule').fullCalendar({
				editable: false,  
				selectable: false,
				selectHelper: false,
				theme: true,
				slotMinutes: 30,
			  	allDaySlot: false,
				defaultView: 'agendaWeek',
				aspectRatio: 0,
				lazyFetching: true,

		        eventSources: [
				{	url: "<%= sources_path(:source => 'Birn1') %>",
					color: "#1E6701" },
				{	url: "<%= sources_path(:source => 'BirnPresents') %>",
					color: "#D90000" },
				{	url: "<%= sources_path(:source => 'Birn2') %>",
					color: "#04576F" },
				{	url: "<%= sources_path(:source => 'shows') %>",
					color: "#2E0927" } ],
						
				eventClick: function(event, jsEvent, view){
					true
				}
			});
		});
	</script>
<% end %>

<div class="one-col">
	<div id="loading"></div>
	<div id="schedule"></div>
</div> <!-- middle -->

app/views/home/stream.html.erb
<div id="stream">
	<% if @channel.present? %>
		<%= content_for :title, @channel.present? ? "Listening to #{@channel[:title]}" : "Select a Channel" %>
		<h3 class="center"><%= @channel[:title] %></h3>
		<% stream_url = "http://streams.thebirn.com/berklee-radio/#{@channel[:file]}" %>
		<div id="audio">
			<audio controls="controls" preload="none" src="<%= stream_url %>" type="audio/mp3" id="stream-player"></audio>
			<div id="temp-loading-spinner"></div><div id="temp-loading-text"></div>
		</div>
	<% end %>
		
	<div id="channel-select" class="center">
		Select a channel: 
		<% HomeController::Channels.each do |channel| %>
			<%= link_to channel[:title], stream_path(:channel => channel[:channel]), :class => "stream-link", "data-channel" => channel[:channel] %>
		<% end %>
	</div>
	
	<% if @channel.present? %>
		<div id="download-stream">
			<a href="#" id="trouble-link">Trouble listening?</a>
			<div id="help">
				You have options!
				<ul>
					<li>If you are using an older browser (earlier than 2009): This stream will work best on the latest version of any of the following:
						<ul>
							<li><a href="http://www.google.com/chrome" target="_blank">Chrome (recommended)</a></li>
							<li><a href="http://www.apple.com/safari/download/" target="_blank">Safari</a></li>
							<li><a href="http://www.mozilla.org/firefox" target="_blank">Firefox</a></li>
							<li><a href="http://www.opera.com/download/" target="_blank">Opera</a></li>
							<li><a href="http://windows.microsoft.com/en-US/internet-explorer/downloads/ie" target="_blank">Internet Explorer</a></li>
						</ul>
					<li>If you're still having trouble, follow these steps:</li>
						<ol>
							<li><%= link_to "Download the stream", stream_url + ".m3u" %> (Right-Click > Save As)</li>
							<li>Open the downloaded file in a media program, such as <a href="http://www.apple.com/itunes/" target="_blank">iTunes</a> or <a href="http://windows.microsoft.com/en-US/windows/products/windows-media-player" target="_blank">Windows Media Player</a></li>
							<li>Your software should connect to the stream and begin playing!</li>
						</ol>
					</li>
				</ul>
			</div> <!-- #help -->
		</div> <!-- #download-stream -->
	<% end %>
	
	<%= link_to "Go to theBirn.com &raquo;".html_safe, root_path, :target => "_blank", :class => "right" %>
</div> <!-- #stream -->

<script>
$("audio").mediaelementplayer({
	audioWidth: 150,
	features: ['playpause','current','volume'],
	success: function(element) {
		element.load();
		element.play();
		element.addEventListener('loadeddata', function(){
			$("#temp-loading-text").empty();
			$("#temp-loading-spinner").spin(false);
		}, false);
		
		element.addEventListener('play', function(){
			$("#temp-loading-text").html("Loading Stream...");
			$("#temp-loading-spinner").spin(minnerSpinner);
		}, false);
		
		element.addEventListener('pause', function(){
			$("#temp-loading-text").html("Stream Stopped");
			$("#temp-loading-spinner").spin(false);
			element.load();
		}, false);
		
		element.addEventListener('ended', function(){
			$("#temp-loading-text").html("Reloading Stream...");
			$("#temp-loading-spinner").spin(minnerSpinner);
			element.load();
			element.play();
		}, false);
	}
});
</script>

<%= content_for :header do %>	
	<script type="text/javascript">
		$(document).ready(function() {
			$('.stream-link').click(function(event) {
				event.preventDefault();
				var channel = $(this).attr('data-channel');
				window.location = '/stream/' + channel;
			});
			
			$('#trouble-link').click(function() { $('#help').toggle(); });
		});
	</script>
<% end %>

app/views/home/update_next_event.js.erb
nextEvent = $("#next-event");
<% unless @next_event.blank? %>
	nextEvent.html("<%= escape_javascript(render :partial => 'next_event', :object => @next_event) %>");
<% else %>
	nextEvent.empty();
<% end %>