config/routes.rb
Tyro::Application.routes.draw do
  
  match 'feed' => 'home#feed'
  match 'display/playlist' => 'display#playlist'
  
  get 'home' => 'home#index', :as => :home
  get 'schedule' => 'home#schedule', :as => :schedule
  get 'sources' => 'home#sources', :as => :sources
  get 'playlist' => 'home#playlist', :as => :playlist
  get 'news' => 'home#news', :as => :news
  get 'blog' => 'blogs#index', :as => :blog
  get 'podcast' => 'podcasts#index', :as => :podcast
  
  get 'update_playlist' => 'home#update_playlist'
  get 'update_current_events' => 'home#update_current_events'  
  get 'update_next_event' => 'home#update_next_event'  
  
  get '/livecam/:cam' => 'home#livecam', :as => :livecam

  match 'explore(/:search_type)' => 'home#explore', :as => :explore
  
  resources :tags, :only => [:index, :show]
    
  get 'about' => 'about#history', :as => :about
  get 'contact' => 'about#contact', :as => :contact
  get 'channels' => 'about#channels', :as => :channels
  get 'submissions' => 'about#submissions', :as => :submissions
  
  get 'stream(/:channel)' => 'home#stream', :as => :stream
  get 'stream/audio/:channel' => 'home#channel_redirect'
  get 'streams/audio/:channel' => 'home#channel_redirect'
    
  resources :shows, :only => :show do
    get 'update_playlist', :on => :collection, :defaults => { :format => :js }
  end
  
  resources :events, :only => [:index, :show] do
    get 'birn1' => 'events#index', :event_type => 'birn1', :on => :collection, :as => :birn1
    get 'birn2' => 'events#index', :event_type => 'birn2', :on => :collection, :as => :birn2
    get 'birn-presents' => 'events#index', :event_type => 'birn-presents', :on => :collection, :as => :birn_presents
  end
    
  get 'join' => 'cp/signups#new', :as => :join
  
  namespace :cp do
    
    match 'login' => 'sessions#new', :as => :login
    match 'logout' => 'sessions#destroy', :as => :logout
    match 'resources' => 'home#resources', :as => :resources
    match 'tin_news' => 'home#tin_news', :as => :tin_news
    
    get "guest-request" => "guest_requests#new", :as => :guest_request
    post "guest-request" => "guest_requests#create", :as => :guest_request
    
    resources :sessions, :only => [:new, :create, :destroy] do 
      get 'emails', :as => :emails, :on => :collection
    end
    
    resource :profile, :only => [:show, :edit, :update] do
      get 'strikes'
      get 'edit_password'
      put 'update_password'
      get 'training_progress'
    end
    
    resources :signups, :news_posts
    resources :static_contents, :only => [:index, :edit, :update]
    
    resources :password_resets, :only => [:new, :create, :edit, :update]
    resources :comments, :except => [:index, :show, :new]
    resources :training_steps, :except => [:show]
        
    resources :schedule_events do
      resources :playlist_entries do
        match 'playlist', :as => :playlist, :on => :collection
      end # playlist_entries
      put 'move' => 'schedule_events#move', :on => :member
      collection do 
        get 'schedule'
        get 'calendar'
        post 'recur'
      end
    end
        
    resources :events do
      get 'playlist', :on => :member
    end
    
    resources :forums, :except => :show do
      resources :topics, :only => [:index, :new, :create] #added index for backwards-compatibility
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
    end #forums
    
    resources :topics, :except => :show do
      resources :messages, :only => [:index, :new, :create] #added index for backwards-compatibility
      collection do
        get 'unread'
        get 'mark_read'
      end
      
      get 'subscribe' => 'subscriptions#subscribe', :as => :subscribe
      get 'unsubscribe' => 'subscriptions#unsubscribe', :as => :unsubscribe
      get '/' => 'messages#index'#, :as => :messages 
    end #topics
    
    resources :messages, :except => :show
    
    resources :problem_reports do      
      member do
        post 'toggle_status'
        get 'comments' => 'problem_reports#show'
      end
      
      resources :comments, :only => :create
    end #problem reports
    
    resources :users do
      resources :comments, :only => :create
      resources :strikes, :except => :show do
        post 'toggle_resolved', :on => :member
      end
      resource :training_progress, :only => [:show, :edit, :update], :controller => 'training_progress'
      
      member do
        get 'edit_password'
        put 'update_password'
        
        get 'comments'
        
        get 'edit_remove'
        put 'remove'
        
        get 'edit_permissions'
        put 'update_permissions'
        
        get 'manage'
        put 'update_manage'
        
        put 'resend_welcome'
      end
      
      collection do
        get 'search'
        get 'new_multiple'
        post 'create_multiple'
      end
    end #users
        
    resources :shows do
      resources :posts, :except => :show
      resources :shouts, :substitutes
      resources :schedule_events, :only => [:index, :new, :create]
      
      collection do
        get 'search'
        get 'full_schedule'
      end
      
      member do
        get 'schedule'
        get 'playlist(/:schedule_event_id)' => 'shows#playlist', :as => :playlist
        get 'edit_manage'
        put 'update_manage'
      end
    end # shows
    
    root :to => 'home#index'  

    if Rails.env.production?
      match '*path' => 'home#index'
    end

  end #cp
  
  root :to => 'home#index'
  
  if Rails.env.production?
    match '*path' => 'home#index'
  end

end

app/controllers/cp/base_controller.rb
class Cp::BaseController < ApplicationController
  before_filter :current_user, :login_required
  layout "cp"
  helper_method :current_user
  
  def login_required
  	return true if current_user
  	session[:return_to] = request.fullpath
  	redirect_to cp_login_path and return false
  end

  private
    def current_user
      @current_user ||= User.includes(:permissions).find(session[:user_id]) if session[:user_id]
    end
    
    def get_tags
      @tags = Tag.scoped
    end
end

app/controllers/cp/comments_controller.rb
class Cp::CommentsController < Cp::BaseController
  before_filter :get_comment, :except => :create
  before_filter :check_permissions, :except => :create
  respond_to :html
  
  def edit
    respond_with @comment
  end
  
  def create
    @comment = get_commentable.comments.build(params[:comment].merge!(:commenter_id => @current_user.id))
    if @comment.save
      flash[:notice] = "Comment added."
      respond_with @comment, :location => [:cp, @comment.commentable, :comments]
    else
      flash[:alert] = "Comment not added."
      redirect_to url_for([:cp, @comment.commentable, :comments])
    end
  end
  
  def update
    flash[:notice] = "Updated comment." if @comment.update_attributes(params[:comment])
    respond_with @comment, :location => [:cp, @comment.commentable, :comments]
  end
  
  def destroy
    if @comment.destroy
      flash[:notice] = "Comment deleted."
    else
      flash[:notice] = "Comment could not be deleted."
    end
    respond_with @comment, :location => [:cp, @comment.commentable, :comments]
  end
  
  private
    def get_commentable
      params.each do |name, value|
        if name =~ /(.+)_id$/
          return $1.classify.constantize.find(value)
        end
      end
      nil
    end
    
    def get_comment
      @comment = Comment.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Comment not found."
        redirect_to cp_root_path
    end
    
    def check_permissions
      return true if @current_user == @comment.commenter or @current_user.allowed_to('admin')
      redirect_to cp_root_path and return false
    end
end

app/controllers/cp/events_controller.rb
class Cp::EventsController < Cp::BaseController
  before_filter :get_event, :only => [:playlist, :show, :edit, :update, :destroy]
  before_filter :check_if_can_manage_this_event, :only => [:playlist, :show, :edit, :update, :destroy]
  before_filter :check_if_can_manage_all_events, :only => [:index, :new, :create, :destroy]
  before_filter :get_tags, :only => [:edit, :new]
  
  respond_to :html, :js

  def index
    respond_with @events = Event.of_type(list).order('schedule_events.starts_at ' + order)
  end
  
  def show
    respond_with @event
  end
  
  def playlist
    respond_with @event
  end
  
  
  def new
    @event = Event.new
    @event.build_schedule_event
  end
  
  def create
    @event = Event.new(params[:event])
    flash[:notice] = "Added event" if @event.save
    respond_with :cp, @event
  end
  
  
  def edit
    respond_with @event
  end
  
  def update
    flash[:notice] = "Updated Special Event" if @event.update_attributes(params[:event])
    respond_with :cp, @event
  end
  
  
  def destroy
    if @event.destroy
      flash[:notice] = "Special Event Removed"
    else
      flash[:alert] = "Special Event could not be removed"
    end
    redirect_to cp_events_path
  end
  
  private    
    def get_event
      @event = Event.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Event not found"
        redirect_to cp_events_path
    end
    
    def check_if_can_manage_this_event
      return true if @current_user.allowed_to('manage_events') or @event.users.include?(@current_user)
      redirect_to cp_root_path and return false
    end
    
    def check_if_can_manage_all_events
      return true if @current_user.allowed_to('manage_events')
      redirect_to cp_root_path and return false
    end
    
    def order
      %w{asc desc}.include?(params[:order]) ? params[:order] : "desc"
    end
    
    helper_method :list
    def list
      ScheduleEvent.get_event_type(params[:list], 'channel')[:id]
    end
end

app/controllers/cp/forums_controller.rb
class Cp::ForumsController < Cp::BaseController
  before_filter :get_forum, :only => [:edit, :update, :destroy]
  before_filter :check_permissions, :except => :index
  
  respond_to :html
  
  def index
    @unread_topics = Topic.unread_by(@current_user)
    respond_with @forums = Forum.all
  end
  
  def new
    respond_with @forum = Forum.new
  end
  
  def create
    @forum = Forum.new(params[:forum])
    flash[:notice] = "Forum created." if @forum.save
    respond_with :cp, @forum, :location => cp_forums_path
  end
  
  
  def edit
  end
  
  def update
    flash[:notice] = "Updated forum." if @forum.update_attributes(params[:forum])
    respond_with :cp, @forum, :location => cp_forums_path
  end
  
  
  def destroy
    if @forum.destroy
      flash[:notice] = "Deleted forum."
    else
      flash[:alert] = "Forum could not be deleted. Try again."
    end
    respond_with :cp, @forum
  end
  
  private
  
    def get_forum
      @forum = Forum.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Forum not found."
        redirect_to cp_forums_path
    end
    
    def check_permissions
      return true if @current_user.allowed_to('admin')
      redirect_to cp_forums_path and return false
    end
end

app/controllers/cp/guest_requests_controller.rb
class Cp::GuestRequestsController < Cp::BaseController
  def new
    @shows = @current_user.shows.active
  end
  
  def create
  end
end

app/controllers/cp/home_controller.rb
class Cp::HomeController < Cp::BaseController
  
  def index
    @latest_topics = Topic.order('updated_at DESC').limit(5)
    @announcements = Topic.global.limit(3)
    @unread_topics = Topic.unread_by(@current_user)
  end
  
  def resources
    @resources = StaticContent.find_by_text_id('resources')
  end
  
  def tin_news
    @tin_news = StaticContent.find_by_text_id('tin_news')
  end
end

app/controllers/cp/messages_controller.rb
class Cp::MessagesController < Cp::BaseController
  before_filter :get_topic, :only => [:index, :new, :create]
  before_filter :get_message, :only => [:edit, :update, :destroy]
  before_filter :check_permissions, :only => [:edit, :update, :destroy]
  before_filter :check_if_locked, :only => [:new, :create, :edit, :update]
  
  respond_to :html
    
  def index
    @message = Message.new
    @unread_topics = Topic.unread_by(@current_user)
    @topic.mark_as_read!(:for => @current_user) if @unread_topics.include?(@topic)
    respond_with @messages = @topic.messages.page(params[:page])
  end  
  
  def new
    respond_with @message = Message.new
  end
  
  def create
    @message = Message.new(params[:message].merge!(:topic_id => @topic.id, :user_id => @current_user.id))
    flash[:notice] = "Message added." if @message.save
    respond_with :cp, @message, :location => cp_topic_messages_path(@topic, :page => @topic.last_page, :anchor => @message.id)
  end
  
  
  def edit
  end
  
  def update
    flash[:notice] = "Updated message." if @message.update_attributes(params[:message])
    respond_with :cp, @message, :location => cp_topic_messages_path(@message.topic, :page => @message.topic.last_page, :anchor => @message.id)
  end
  
  
  def destroy
    if @message.destroy
      flash[:notice] = "Deleted message."
    else
      flash[:alert] = "Message could not be deleted. Try again."
    end
    respond_with :cp, @message.topic, :messages
  end
  
  private
    def get_topic
      @topic = Topic.find(params[:topic_id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Topic not found."
        redirect_to cp_forums_path
    end
    
    def get_message
      @message = Message.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Message not found."
        redirect_to cp_forums_path
    end
    
    def check_permissions
      return true if @current_user.allowed_to('admin') or @message.user == @current_user
      redirect_to cp_topic_messages_path(@topic) and return false
    end
    
    def check_if_locked
      @topic ||= @message.topic
      return true if !@topic.locked
      flash[:alert] = "This topic is locked. It is not accepting any changes or new replies."
      redirect_to cp_topic_messages_path(@topic) and return false
    end
end

app/controllers/cp/news_posts_controller.rb
class Cp::NewsPostsController < Cp::BaseController
  before_filter :check_permissions
  before_filter :get_news_post, :except => [:index, :new, :create]
  
  respond_to :html
  def index
    respond_with @news_posts = NewsPost.page(params[:page]).per(5)
  end
  
  def show
    respond_with @news_post
  end
  
  
  def new
    respond_with @news_post = NewsPost.new
  end
  
  def create
    @news_post = NewsPost.new(params[:news_post])
    if @news_post.save
      flash[:notice] = "Added News Post" 
      redirect_to cp_news_posts_path
    else
      respond_with [:cp, @news_post]
    end
  end
  
  
  def edit
    respond_with @news_post
  end
  
  def update
    if @news_post.update_attributes(params[:news_post])
      flash[:notice] = "Updated News Post"
      redirect_to cp_news_posts_path
    else
      respond_with [:cp, @news_post]
    end
  end
  
  
  def destroy
    if @news_post.destroy
      flash[:notice] = "Removed News Post"
    else
      flash[:alert] = "Could not removed News Post"
    end
    respond_with [:cp, @news_post]
  end
  
  protected
    def check_permissions
      return true if @current_user.allowed_to('manage_news_posts')
      redirect_to cp_root_path and return false
    end
    
    def get_news_post
      @news_post = NewsPost.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to cp_news_posts_path, :alert => "News Post not found."
    end
end

app/controllers/cp/password_resets_controller.rb
class Cp::PasswordResetsController < Cp::BaseController
  skip_before_filter :login_required

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    user.send_password_reset if user
    redirect_to cp_login_path, :notice => "Password reset instructions sent to #{params[:email]}"
  end
  
  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end
  
  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_requested_at < 30.minutes.ago
      redirect_to new_cp_password_reset_path, :alert => "Password reset has expired. Request another reset."
    else
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]
      if @user.save
        redirect_to cp_login_path, :notice => "Password has been reset."
      else
        render :edit
      end
    end
  end
end

app/controllers/cp/permissions_controller.rb
class Cp::PermissionsController < Cp::BaseController
  before_filter :check_if_can_admin # admins only in here
  before_filter :get_permission, :only => [:edit, :update]
  before_filter :get_living_users, :only => [:edit, :update]
  
  respond_to :html
  
  def index
    respond_with(@permissions = Permission.includes(:users).all)
  end
  
  def edit
    respond_with @permission
  end
  
  def update
    params[:permission][:user_ids] ||= []
    flash[:notice] = "Updated Permission." if @permission.update_attributes(params[:permission])
    respond_with @permission
  end

  def update_all_permissions
    params[:permission].keys.each do |id|
      @permission = Permission.find(id)
      @permission.update_attributes(params[:permission][id])
    end
    
    flash[:notice] = "Updated Grid."
    respond_with @permission
  end
  
  private
    def check_if_can_admin
      return true if @current_user.allowed_to('admin')
      redirect_to cp_root_path and return false
    end
    
    def get_permission
      @permission = Permission.includes(:users).find(params[:id]) 
    end
    
    def get_users
      @users = User.all
    end
end

app/views/cp/topics/_legend.html.erb
<div class="legend">
	<%= image_tag "icons/locked Yellow.png", :class => "topic-icon" %> Locked<br />
	<%= image_tag "icons/earth Green.png", :class => "topic-icon" %> Global/Announcement<br />
	<%= image_tag "icons/about Blue.png", :class => "topic-icon" %> Sticky
</div>

app/views/cp/topics/_topic.html.erb
<div class='item topic linked'>
	<div class='status'><%= image_tag unread_topics.include?(topic) ? 'icons/Knob Green.png' : 'icons/Knob Grey.png' %></div>
	<div class='info'>
		<div class='subject'><%= link_to topic.title, cp_topic_messages_path(topic) %></div>
		<div class='description'>
			Started by <%= topic.user.name %> <%= distance_of_time_in_words(Time.zone.now, topic.created_at) %> ago.
			<div class="status-icons">
				<% if topic.locked %><div class="locked right">&nbsp;</div><% end %>
				<% if topic.global %><div class="global right">&nbsp;</div><% end %>
				<% if topic.sticky %><div class="sticky right">&nbsp;</div><% end %>
			</div>
		</div>
	</div>
	<div class='last-post'>
		<% unless topic.replies == 0 %>
			<strong><%= topic.replies %></strong> replies.<br />
			<%= link_to "Latest #{distance_of_time_in_words(Time.zone.now, topic.updated_at)} ago", cp_topic_messages_path(topic, :page => topic.last_page, :anchor => topic.most_recent_reply.id) %>
		<% else %>
			No replies yet.
		<% end %>
	</div>
	<div class='clear'></div>
</div>	

app/views/cp/topics/_topic_form.html.erb
  <li>
	<label for="title">Title</label>
	<%= topic_form.text_field :title %>
  </li>
  <% if @current_user.allowed_to('manage_forums') %>
	  <li>
		<label for="forum">Forum</label>
		<%= topic_form.select :forum_id, Forum.all.map { |f| [f.subject, f.id] }, :selected => forum.id %>
	  </li>

	  <li class="checkboxes">
		<label for="locked">Locked?</label>
		<%= topic_form.check_box :locked %>
	  </li>

	  <li class="checkboxes">
		<label for="global">Global?</label>
		<%= topic_form.check_box :global %>
	  </li>

	  <li class="checkboxes">
		<label for="sticky">Sticky?</label>
		<%= topic_form.check_box :sticky %>
	  </li>
  <% end %>

app/views/cp/topics/edit.html.erb
<%= forum_header(:forum => @topic.forum) { } %>

<%= box_wrapper nil, :no_tabs => true do %>
	<%= form_for [:cp, @topic] do |f| %>
		<legend>Edit Topic: <%= @topic.title %></legend>
	  	<%= check_for_errors(@topic) %>
	
		<fieldset>
			<ol>
				<%= render :partial => 'topic_form', :object => f, :locals => { :topic => @topic, :forum => @topic.forum } %>
				<%= f.fields_for :initial_message do |m| %> 
					<%= reply_box do %>
						<%= render :partial => '/cp/messages/message_form', :object => m %>
					<% end %>
				<% end %>
			</ol>
		</fieldset>
		
	  	<fieldset>
	    	<%= f.submit "Update Topic" %>
	  	</fieldset>
	<% end %>
	<%= link_to "Remove Topic", cp_topic_path(@topic), :method => 'delete', :confirm => "Remove this topic?", :class => 'delete-link' %>
<% end %>

app/views/cp/topics/index.html.erb
<%= forum_header(:forum => @forum) do %>
	<%= add_button 'Start Topic', new_cp_forum_topic_path(@forum) %>
<% end %>

<%= paginate @topics %>
	<div id='forum-list'>
		<%= render :partial => 'topic', :collection => @topics, :locals => { :unread_topics => @unread_topics } %>
		<%= no_records_check(@topics, "Topics") %>
	</div>
<%= paginate @topics %>

<%= render :partial => 'legend' %>
<%= render :partial => 'cp/subscriptions/subscribe', :locals => { :record => @forum } %>

app/views/cp/topics/new.html.erb
<%= forum_header(:forum => @forum) {} %>

<%= box_wrapper nil, :no_tabs => true do %>
	<%= form_for [:cp, @forum, @topic] do |f| %>
		<legend>Start Topic</legend>
	  	<%= check_for_errors(@topic) %>
	
		<fieldset>
			<ol>
				<%= render :partial => 'topic_form', :object => f, :locals => { :topic => @topic, :forum => @forum } %>
				<%= f.fields_for :initial_message do |m| %> 
					<%= reply_box do %>
						<%= render :partial => '/cp/messages/message_form', :object => m, :locals => { :topic => @topic, :forum => @forum } %>
					<% end %>
				<% end %>
			</ol>
		</fieldset>
		
	  	<fieldset>
	    	<%= f.submit "Start Topic" %>
	  	</fieldset>
	<% end %>
<% end %>

app/views/cp/topics/unread.html.erb
<%= forum_header(:title => "Unread Topics") do %>
	<%= add_button('Mark All Read', mark_read_cp_topics_path) if @unread_topics.present? %>
<% end %>

<%= paginate @topics %>
	<div id='forum-list'>
		<%= render :partial => 'topic', :collection => @topics, :locals => { :unread_topics => @unread_topics } %>
		<%= no_records_check(@topics, "Unread Topics", :message => "You are all caught up!") %>
	</div>
<%= paginate @topics %>
<%= render :partial => 'legend' %>